### ISSUE TITLE
📄 Feedback to the first draft of `Exam.sol`

### ISSUE THREAD

**Issue by EG-easy** [openreachtech/onchain-examination-contract#1]
### About `revealCorrects`

```solidity
    function revealCorrects(
        bytes calldata corrects_,
        bytes calldata points_,
        bytes calldata pointsMultiplier_
    ) public onlyOwner {
        // assure that the hash of corrects is equal to correctAnswerHash
        require(keccak256(corrects_) == correctAnswerHash, "invalid corrects");  // <- here

        corrects = corrects_;
        points = points_;
        pointsMultiplier = pointsMultiplier_;
    }
```

The current code simply hashes and matches with revealCorrects, but I think it needs to include ModelAnswerSalt and hashing.
Otherwise, a simple Exam, like a multiple choice question, can predict the answer by brute force.

> 現在のコードではrevealCorrectsで単純にハッシュ化して突合していますが、ModelAnswerSaltを含めてハッシュ化が必要だと思います。そうしないと選択式問題のような単純なExamでは解答を総当りで予測できてしまいます。

### About calculateScore

I think that before `calculateScore`, the participants will need to perform an action to reveal their answers.
First, in `submitAnswer` (`commitAnswer` might be better), participants also register their hashed values with AnswerSalt and Answer.

Then, the participant records his/her raw answer data in the contract, either in or in front of `calculateScore`.

Without this action, it is possible to guess the answers of other respondents.

> calculateScoreの前に参加者が自分の解答をrevealする動作が必要になると思います。
まず、submitAnswer（commitAnswerのほうが良いかも）で参加者もAnswerSaltとAnswerでハッシュ化した値を登録しておきます。
その後、calculateScoreの中か前で自分の生の解答データをコントラクトに記録します。
この動作をしないと他の回答者の答えを推測することができてしまいます。

## Tasks

- [ ]

**Comment by tak1827** [comment]
fixed #2
